<a href="https://colab.research.google.com/github/harshitsonitech-eng/IDRA-Assignments/blob/main/Cleaned_Company_Employee_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import glob
import os

from google.colab import files

uploaded = files.upload()

print("Uploaded files:")
for f in uploaded:
    print(f)

Saving Day11_Messy_Company_Employee_Dataset.csv to Day11_Messy_Company_Employee_Dataset.csv
Uploaded files:
Day11_Messy_Company_Employee_Dataset.csv

In [2]:
csv_files = glob.glob("*.csv")

if len(csv_files) == 0:
    raise FileNotFoundError("CSV file not found.")

file_name = csv_files[0]
df = pd.read_csv(file_name)

df.columns = df.columns.str.strip()

print("File loaded:", file_name)
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

display(df.head())

File loaded: Day11_Messy_Company_Employee_Dataset.csv
Shape: (157, 12)

Columns:
['Employee_ID', 'Employee_Name', 'Department', 'Job_Title', 'Age', 'Gender', 'Annual_Salary', 'Experience_Years', 'Joining_Date', 'City', 'Performance_Score', 'Work_Mode']

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,NaN,Data Scientist,48.0,Other,108371.0,13.2,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.1,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.2,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,NaN,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.9,2018-07-24,Hyderabad,4.0,Hybrid

In [3]:
print("Dataset Information:")
df.info()

print("\nShape:", df.shape)

print("\nData Types:")
print(df.dtypes)

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        157 non-null    object
 1   Employee_Name      157 non-null    object
 2   Department         152 non-null    object
 3   Job_Title          157 non-null    object
 4   Age                153 non-null    float64
 5   Gender             152 non-null    object
 6   Annual_Salary      152 non-null    float64
 7   Experience_Years   154 non-null    float64
 8   Joining_Date       157 non-null    object
 9   City               152 non-null    object
 10  Performance_Score  154 non-null    float64
 11  Work_Mode          155 non-null    object
dtypes: float64(4), object(8)
memory usage: 14.8+ KB

Shape: (157, 12)

Data Types:
Employee_ID           object
Employee_Name         object
Department            object
Job_Title             object
Age                  float64
Gender                object
Annual_Salary        float64
Experience_Years     float64
Joining_Date          object
City                  object
Performance_Score    float64
Work_Mode             object
dtype: object

In [4]:
print("Missing Values Before Cleaning:")

missing_values = df.isnull().sum()

display(missing_values[missing_values > 0])

print("\nTotal missing values:", df.isnull().sum().sum())

Missing Values Before Cleaning:

Department           5
Age                  4
Gender               5
Annual_Salary        5
Experience_Years     3
City                 5
Performance_Score    3
Work_Mode            2
dtype: int64

Total missing values: 32

In [5]:
duplicate_count = df.duplicated().sum()

print("Duplicate records:", duplicate_count)

Duplicate records: 7

In [6]:
categorical_columns = [
    "Department",
    "Job_Title",
    "Gender",
    "City",
    "Work_Mode"
]

for col in categorical_columns:
    print("\n", col)
    print(df[col].astype(str).str.strip().value_counts().head(20))

 Department
Department
Marketing           23
Engineering         21
Customer Success    20
Finance             19
Sales               19
Operations          17
Human Resources     16
Data & Analytics    15
nan                  5
ENGINEERING          1
engineering          1
Name: count, dtype: int64

 Job_Title
Job_Title
Data Scientist                    13
Senior Software Engineer          11
Marketing Executive               10
Sales Manager                      9
Financial Analyst                  9
Support Specialist                 8
Content Strategist                 8
Customer Success Manager           7
HR Executive                       7
Business Development Executive     7
QA Engineer                        7
Process Analyst                    6
Accountant                         6
Marketing Manager                  6
HR Manager                         6
Customer Success Executive         6
Operations Executive               6
Operations Manager                 6
Sales Executive                    5
Recruiter                          4
Name: count, dtype: int64

 Gender
Gender
Male      75
Female    68
Other      7
nan        5
female     1
MALE       1
Name: count, dtype: int64

 City
City
Chandigarh    24
Pune          23
Jaipur        18
Mumbai        15
Hyderabad     14
Srinagar      13
Bengaluru     12
Delhi         12
Chennai       10
Kolkata        9
nan            5
delhi          1
DELHI          1
Name: count, dtype: int64

 Work_Mode
Work_Mode
Remote    56
Hybrid    50
Office    47
nan        2
REMOTE     1
remote     1
Name: count, dtype: int64

In [8]:
numeric_columns = [
    "Age",
    "Annual_Salary",
    "Experience_Years",
    "Performance_Score"
]

for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df["Joining_Date"] = pd.to_datetime(
    df["Joining_Date"],
    errors="coerce",
    dayfirst=True
)

print("Data types corrected.")

print(df.dtypes)

Data types corrected.
Employee_ID                  object
Employee_Name                object
Department                   object
Job_Title                    object
Age                         float64
Gender                       object
Annual_Salary               float64
Experience_Years            float64
Joining_Date         datetime64[ns]
City                         object
Performance_Score           float64
Work_Mode                    object
dtype: object

/tmp/ipykernel_3505/3843793132.py:11: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df["Joining_Date"] = pd.to_datetime(

In [10]:
numeric_columns = [
    "Age",
    "Annual_Salary",
    "Experience_Years",
    "Performance_Score"
]

for col in numeric_columns:
    df[col] = df[col].fillna(df[col].median())

print("Numeric missing values filled using median.")
print(df[numeric_columns].isnull().sum())

Numeric missing values filled using median.
Age                  0
Annual_Salary        0
Experience_Years     0
Performance_Score    0
dtype: int64

In [11]:
categorical_columns = [
    "Department",
    "Job_Title",
    "Gender",
    "City",
    "Work_Mode"
]

for col in categorical_columns:
    if df[col].isnull().any():
        mode_value = df[col].mode()

        if len(mode_value) > 0:
            df[col] = df[col].fillna(mode_value[0])

print("Categorical missing values filled using mode.")
print(df[categorical_columns].isnull().sum())

Categorical missing values filled using mode.
Department    0
Job_Title     0
Gender        0
City          0
Work_Mode     0
dtype: int64

In [12]:
df["Joining_Date"] = df["Joining_Date"].ffill()

print("Joining_Date missing values after forward fill:")
print(df["Joining_Date"].isnull().sum())

Joining_Date missing values after forward fill:
0

In [13]:
text_columns = [
    "Employee_ID",
    "Employee_Name",
    "Department",
    "Job_Title",
    "Gender",
    "City",
    "Work_Mode"
]

for col in text_columns:
    df[col] = df[col].astype(str).str.strip()

df["Gender"] = df["Gender"].replace({
    "M": "Male",
    "m": "Male",
    "F": "Female",
    "f": "Female",
    "N/A": "Other",
    "NA": "Other"
})

df["Work_Mode"] = df["Work_Mode"].replace({
    "office": "Office",
    "OFFICE": "Office",
    "remote": "Remote",
    "REMOTE": "Remote",
    "hybrid": "Hybrid",
    "HYBRID": "Hybrid"
})

print("Text values cleaned and standardized.")

Text values cleaned and standardized.

In [14]:
before_duplicates = len(df)

df = df.drop_duplicates()

after_duplicates = len(df)

print("Rows before removing duplicates:", before_duplicates)
print("Rows after removing duplicates:", after_duplicates)
print("Duplicates removed:", before_duplicates - after_duplicates)

Rows before removing duplicates: 157
Rows after removing duplicates: 150
Duplicates removed: 7

In [15]:
print("----- FINAL CLEANING CHECK -----")

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nRemaining Missing Values:")
print(df.isnull().sum())

print("\nRemaining Duplicate Rows:")
print(df.duplicated().sum())

print("\nFinal Data Types:")
print(df.dtypes)

display(df.head(10))

----- FINAL CLEANING CHECK -----
Rows: 150
Columns: 12

Remaining Missing Values:
Employee_ID          0
Employee_Name        0
Department           0
Job_Title            0
Age                  0
Gender               0
Annual_Salary        0
Experience_Years     0
Joining_Date         0
City                 0
Performance_Score    0
Work_Mode            0
dtype: int64

Remaining Duplicate Rows:
0

Final Data Types:
Employee_ID                  object
Employee_Name                object
Department                   object
Job_Title                    object
Age                         float64
Gender                       object
Annual_Salary               float64
Experience_Years            float64
Joining_Date         datetime64[ns]
City                         object
Performance_Score           float64
Work_Mode                    object
dtype: object

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,Marketing,Data Scientist,48.0,Other,108371.0,13.20,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.10,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.20,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,9.35,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.90,2018-07-24,Hyderabad,4.0,Hybrid
5,EMP0117,Zoya Kapoor,Finance,Finance Manager,42.0,Male,128567.0,15.40,2017-08-02,Chennai,4.0,Hybrid
6,EMP0081,Maryam Mir,Marketing,Content Strategist,37.0,Male,58878.0,1.80,2024-01-18,Pune,2.0,Office
7,EMP0026,Omar Das,Engineering,QA Engineer,38.0,Male,112276.0,12.00,2019-05-14,Chandigarh,4.0,Hybrid
8,EMP0129,Dev Ahmed,Data & Analytics,Data Scientist,45.0,Male,135730.0,14.10,2021-01-27,Srinagar,2.0,Remote
9,EMP0121,Karan Patel,Data & Analytics,BI Analyst,40.0,Female,101886.0,8.50,2020-06-28,Chennai,4.0,Remote

In [16]:
print("----- BEFORE vs AFTER CLEANING -----")

print("Original rows:", len(pd.read_csv(file_name)))
print("Cleaned rows:", len(df))

print("\nOriginal columns:", len(pd.read_csv(file_name).columns))
print("Cleaned columns:", len(df.columns))

print("\nRemaining missing values:", df.isnull().sum().sum())
print("Remaining duplicate rows:", df.duplicated().sum())

----- BEFORE vs AFTER CLEANING -----
Original rows: 157
Cleaned rows: 150

Original columns: 12
Cleaned columns: 12

Remaining missing values: 0
Remaining duplicate rows: 0

In [17]:
print("""
CLEANING SUMMARY

1. Loaded the company employee dataset using Pandas.
2. Inspected dataset shape, columns and data types.
3. Identified missing values.
4. Converted numeric columns to appropriate numeric data types.
5. Converted Joining_Date into datetime format.
6. Filled numeric missing values using median.
7. Filled categorical missing values using mode.
8. Used forward filling for missing joining dates.
9. Removed extra spaces from text values.
10. Standardized inconsistent categorical entries.
11. Removed duplicate records.
12. Verified the dataset after cleaning.
""")

CLEANING SUMMARY

1. Loaded the company employee dataset using Pandas.
2. Inspected dataset shape, columns and data types.
3. Identified missing values.
4. Converted numeric columns to appropriate numeric data types.
5. Converted Joining_Date into datetime format.
6. Filled numeric missing values using median.
7. Filled categorical missing values using mode.
8. Used forward filling for missing joining dates.
9. Removed extra spaces from text values.
10. Standardized inconsistent categorical entries.
11. Removed duplicate records.
12. Verified the dataset after cleaning.

In [18]:
output_file = "Day11_Cleaned_Company_Employee_Dataset.csv"

df.to_csv(
    output_file,
    index=False
)

print("SUCCESS! Cleaned dataset exported successfully.")
print("File name:", output_file)
print("File size:", os.path.getsize(output_file), "bytes")

SUCCESS! Cleaned dataset exported successfully.
File name: Day11_Cleaned_Company_Employee_Dataset.csv
File size: 15698 bytes

In [19]:
final_df = pd.read_csv("Day11_Cleaned_Company_Employee_Dataset.csv")

print("Final CSV verified successfully!")
print("Shape:", final_df.shape)

display(final_df.head(10))

Final CSV verified successfully!
Shape: (150, 12)

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,Marketing,Data Scientist,48.0,Other,108371.0,13.20,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.10,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.20,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,9.35,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.90,2018-07-24,Hyderabad,4.0,Hybrid
5,EMP0117,Zoya Kapoor,Finance,Finance Manager,42.0,Male,128567.0,15.40,2017-08-02,Chennai,4.0,Hybrid
6,EMP0081,Maryam Mir,Marketing,Content Strategist,37.0,Male,58878.0,1.80,2024-01-18,Pune,2.0,Office
7,EMP0026,Omar Das,Engineering,QA Engineer,38.0,Male,112276.0,12.00,2019-05-14,Chandigarh,4.0,Hybrid
8,EMP0129,Dev Ahmed,Data & Analytics,Data Scientist,45.0,Male,135730.0,14.10,2021-01-27,Srinagar,2.0,Remote
9,EMP0121,Karan Patel,Data & Analytics,BI Analyst,40.0,Female,101886.0,8.50,2020-06-28,Chennai,4.0,Remote