<a href="https://colab.research.google.com/github/harshitsonitech-eng/IDRA-Assignments/blob/main/Day7_Dataset_Summary_Reort.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

from google.colab import files

uploaded = files.upload()

Saving Day7_Student_Dataset.csv to Day7_Student_Dataset (1).csv

In [3]:
df = pd.read_csv("Day7_Student_Dataset (1).csv")

print("Dataset loaded successfully!")
df.head()

Dataset loaded successfully!

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow

In [4]:
print("First 5 Rows:")
display(df.head())

print("\nLast 5 Rows:")
display(df.tail())

print("\nRandom Samples:")
display(df.sample(5))

First 5 Rows:

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow

Last 5 Rows:

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

Random Samples:

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
19,1020,Priya Menon,21,AI,90.0,91.0,Chennai
16,1017,Dev Patel,19,AI,86.0,89.0,Ahmedabad
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

In [5]:
print("Dataset Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nIndex:")
print(df.index)

Dataset Shape: (25, 7)

Columns:
['Student_ID', 'Name', 'Age', 'Course', 'Marks', 'Attendance_Percentage', 'City']

Index:
RangeIndex(start=0, stop=25, step=1)

In [6]:
print("Data Types:")
print(df.dtypes)

Data Types:
Student_ID                 int64
Name                      object
Age                        int64
Course                    object
Marks                    float64
Attendance_Percentage    float64
City                      object
dtype: object

In [7]:
print("Dataset Information:")
df.info()

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             25 non-null     int64
 1   Name                   25 non-null     object
 2   Age                    25 non-null     int64
 3   Course                 25 non-null     object
 4   Marks                  24 non-null     float64
 5   Attendance_Percentage  24 non-null     float64
 6   City                   24 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 1.5+ KB

In [8]:
print("Descriptive Statistics:")
display(df.describe())

Descriptive Statistics:

        Student_ID        Age      Marks  Attendance_Percentage
count    25.000000  25.000000  24.000000              24.000000
mean   1013.000000  20.000000  82.250000              87.083333
std       7.359801   1.414214   8.689074               7.252686
min    1001.000000  18.000000  68.000000              72.000000
25%    1007.000000  19.000000  75.500000              82.750000
50%    1013.000000  20.000000  82.500000              88.000000
75%    1019.000000  21.000000  89.250000              92.250000
max    1025.000000  23.000000  96.000000              98.000000

In [9]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Student_ID               0
Name                     0
Age                      0
Course                   0
Marks                    1
Attendance_Percentage    1
City                     1
dtype: int64

In [10]:
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

print("\nAvailable Features:")
for column in df.columns:
    print("-", column)

print("\nMissing Values:")
missing = df.isnull().sum()
print(missing[missing > 0])

Number of Rows: 25
Number of Columns: 7

Available Features:
- Student_ID
- Name
- Age
- Course
- Marks
- Attendance_Percentage
- City

Missing Values:
Marks                    1
Attendance_Percentage    1
City                     1
dtype: int64