<a href="https://colab.research.google.com/github/harshitsonitech-eng/IDRA-Assignments/blob/main/Processed_E_commeres_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
from google.colab import files

uploaded = files.upload()

print("Uploaded files:")
for file in uploaded:
    print(file)

Saving Day9_Orders.csv to Day9_Orders.csv
Saving Day9_Customers.csv to Day9_Customers.csv
Saving Day9_Products.csv to Day9_Products (1).csv
Uploaded files:
Day9_Orders.csv
Day9_Customers.csv
Day9_Products (1).csv

In [4]:
import pandas as pd

orders = pd.read_csv("Day9_Orders.csv")
customers = pd.read_csv("Day9_Customers.csv")
products = pd.read_csv("Day9_Products (1).csv")

print("Orders:")
print(orders.shape)
print(orders.columns.tolist())

print("\nCustomers:")
print(customers.shape)
print(customers.columns.tolist())

print("\nProducts:")
print(products.shape)
print(products.columns.tolist())

Orders:
(120, 7)
['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Quantity', 'Payment_Method', 'Order_Status']

Customers:
(30, 5)
['Customer_ID', 'Customer_Name', 'City', 'Region', 'Membership_Type']

Products:
(20, 5)
['Product_ID', 'Product_Name', 'Category', 'Unit_Price', 'Brand']

In [5]:
import pandas as pd
import glob
import os

print("Available CSV files:")

for file in glob.glob("*.csv"):
    print(file)

Available CSV files:
Day9_Customers.csv
Day9_Products.csv
Day9_Products (1).csv
Day9_Orders.csv

In [6]:
orders_file = "Day9_Orders.csv"
customers_file = "Day9_Customers.csv"

product_files = glob.glob("Day9_Products*.csv")

if len(product_files) == 0:
    raise FileNotFoundError("Day9_Products CSV nahi mili.")

products_file = product_files[0]

orders = pd.read_csv(orders_file)
customers = pd.read_csv(customers_file)
products = pd.read_csv(products_file)

orders.columns = orders.columns.str.strip()
customers.columns = customers.columns.str.strip()
products.columns = products.columns.str.strip()

print("Orders:", orders.shape)
print("Customers:", customers.shape)
print("Products:", products.shape)

print("\nOrders Columns:")
print(orders.columns.tolist())

print("\nCustomers Columns:")
print(customers.columns.tolist())

print("\nProducts Columns:")
print(products.columns.tolist())

Orders: (120, 7)
Customers: (30, 5)
Products: (20, 5)

Orders Columns:
['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Quantity', 'Payment_Method', 'Order_Status']

Customers Columns:
['Customer_ID', 'Customer_Name', 'City', 'Region', 'Membership_Type']

Products Columns:
['Product_ID', 'Product_Name', 'Category', 'Unit_Price', 'Brand']

In [7]:
print("ORDERS")
display(orders.head())

print("\nCUSTOMERS")
display(customers.head())

print("\nPRODUCTS")
display(products.head())

ORDERS

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered

CUSTOMERS

  Customer_ID Customer_Name      City Region Membership_Type
0        C001  Aarav Sharma  Srinagar  North         Premium
1        C002     Zoya Khan     Delhi  North         Regular
2        C003   Rohan Mehta    Mumbai   West         Premium
3        C004  Ananya Singh     Jammu  North         Regular
4        C005     Kabir Ali   Lucknow  North             New

PRODUCTS

  Product_ID         Product_Name     Category  Unit_Price     Brand
0       P001  Wireless Headphones  Electronics        1499  SoundMax
1       P002  Mechanical Keyboard  Electronics        2499    KeyPro
2       P003       Wireless Mouse  Electronics         899  TechGear
3       P004          Smart Watch  Electronics        3299   FitTech
4       P005           Power Bank  Electronics        1199  VoltPlus

In [8]:
print("Orders Missing Values:")
print(orders.isnull().sum())

print("\nCustomers Missing Values:")
print(customers.isnull().sum())

print("\nProducts Missing Values:")
print(products.isnull().sum())

print("\nOrders Data Types:")
print(orders.dtypes)

print("\nCustomers Data Types:")
print(customers.dtypes)

print("\nProducts Data Types:")
print(products.dtypes)

Orders Missing Values:
Order_ID          0
Order_Date        0
Customer_ID       0
Product_ID        0
Quantity          0
Payment_Method    0
Order_Status      0
dtype: int64

Customers Missing Values:
Customer_ID        0
Customer_Name      0
City               0
Region             0
Membership_Type    0
dtype: int64

Products Missing Values:
Product_ID      0
Product_Name    0
Category        0
Unit_Price      0
Brand           0
dtype: int64

Orders Data Types:
Order_ID          object
Order_Date        object
Customer_ID       object
Product_ID        object
Quantity           int64
Payment_Method    object
Order_Status      object
dtype: object

Customers Data Types:
Customer_ID        object
Customer_Name      object
City               object
Region             object
Membership_Type    object
dtype: object

Products Data Types:
Product_ID      object
Product_Name    object
Category        object
Unit_Price       int64
Brand           object
dtype: object

In [9]:
merged_data = pd.merge(
    orders,
    customers,
    on="Customer_ID",
    how="left"
)

print("After Orders + Customers merge:")
print(merged_data.shape)

display(merged_data.head())

After Orders + Customers merge:
(120, 11)

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New

In [10]:
merged_data = pd.merge(
    merged_data,
    products,
    on="Product_ID",
    how="left",
    suffixes=("", "_Product")
)

print("Final merged shape:")
print(merged_data.shape)

display(merged_data.head())

Final merged shape:
(120, 15)

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew

In [11]:
part1 = merged_data.iloc[:10]
part2 = merged_data.iloc[10:]

processed_data = pd.concat(
    [part1, part2],
    ignore_index=True
)

print("Data after concat():")
print(processed_data.shape)

display(processed_data.head())

Data after concat():
(120, 15)

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew

In [12]:
processed_data["Order_Date"] = pd.to_datetime(
    processed_data["Order_Date"],
    dayfirst=True,
    errors="coerce"
)

processed_data["Order_Month"] = processed_data["Order_Date"].dt.month
processed_data["Order_Day"] = processed_data["Order_Date"].dt.day
processed_data["Order_Day_Name"] = processed_data["Order_Date"].dt.day_name()

print("DateTime operations completed.")

display(
    processed_data[
        ["Order_Date", "Order_Month", "Order_Day", "Order_Day_Name"]
    ].head()
)

DateTime operations completed.

/tmp/ipykernel_645/989809507.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  processed_data["Order_Date"] = pd.to_datetime(

  Order_Date  Order_Month  Order_Day Order_Day_Name
0 2026-02-19            2         19       Thursday
1 2026-01-25            1         25         Sunday
2 2026-02-26            2         26       Thursday
3 2026-03-04            3          4      Wednesday
4 2026-03-29            3         29         Sunday

In [13]:
processed_data["Quantity"] = pd.to_numeric(
    processed_data["Quantity"],
    errors="coerce"
)

processed_data["Unit_Price"] = pd.to_numeric(
    processed_data["Unit_Price"],
    errors="coerce"
)

processed_data["Customer_Name_Clean"] = processed_data["Customer_Name"].apply(
    lambda x: str(x).strip().title()
)

processed_data["Calculated_Total"] = (
    processed_data["Quantity"] * processed_data["Unit_Price"]
)

print("apply() and calculated columns completed.")

display(
    processed_data[
        [
            "Customer_Name",
            "Customer_Name_Clean",
            "Quantity",
            "Unit_Price",
            "Calculated_Total"
        ]
    ].head()
)

apply() and calculated columns completed.

   Customer_Name Customer_Name_Clean  Quantity  Unit_Price  Calculated_Total
0  Harsh Vardhan       Harsh Vardhan         2        2499              4998
1   Ishita Gupta        Ishita Gupta         2         899              1798
2    Karan Joshi         Karan Joshi         1        3299              3299
3    Maryam Khan         Maryam Khan         3         999              2997
4   Reyansh Jain        Reyansh Jain         5        3499             17495

In [14]:
print("Final Processed Dataset")
print("Rows:", processed_data.shape[0])
print("Columns:", processed_data.shape[1])

print("\nColumns:")
print(processed_data.columns.tolist())

print("\nMissing Values:")
print(processed_data.isnull().sum())

display(processed_data.head(10))

Final Processed Dataset
Rows: 120
Columns: 20

Columns:
['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Quantity', 'Payment_Method', 'Order_Status', 'Customer_Name', 'City', 'Region', 'Membership_Type', 'Product_Name', 'Category', 'Unit_Price', 'Brand', 'Order_Month', 'Order_Day', 'Order_Day_Name', 'Customer_Name_Clean', 'Calculated_Total']

Missing Values:
Order_ID               0
Order_Date             0
Customer_ID            0
Product_ID             0
Quantity               0
Payment_Method         0
Order_Status           0
Customer_Name          0
City                   0
Region                 0
Membership_Type        0
Product_Name           0
Category               0
Unit_Price             0
Brand                  0
Order_Month            0
Order_Day              0
Order_Day_Name         0
Customer_Name_Clean    0
Calculated_Total       0
dtype: int64

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand,Order_Month,Order_Day,Order_Day_Name,Customer_Name_Clean,Calculated_Total
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro,2,19,Thursday,Harsh Vardhan,4998
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear,1,25,Sunday,Ishita Gupta,1798
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech,2,26,Thursday,Karan Joshi,3299
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress,3,4,Wednesday,Maryam Khan,2997
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew,3,29,Sunday,Reyansh Jain,17495
5,O0006,2026-02-09,C003,P018,3,UPI,Delivered,Rohan Mehta,Mumbai,West,Premium,Football,Sports,799,SportZone,2,9,Monday,Rohan Mehta,2397
6,O0007,2026-02-10,C011,P003,3,UPI,Delivered,Vivaan Kapoor,Jaipur,North,New,Wireless Mouse,Electronics,899,TechGear,2,10,Tuesday,Vivaan Kapoor,2697
7,O0008,2026-03-27,C020,P005,4,Debit Card,Delivered,Priya Menon,Chennai,South,Premium,Power Bank,Electronics,1199,VoltPlus,3,27,Friday,Priya Menon,4796
8,O0009,2026-03-13,C024,P009,2,UPI,Cancelled,Maryam Khan,Hyderabad,South,Regular,Coffee Maker,Home & Kitchen,3499,HomeBrew,3,13,Friday,Maryam Khan,6998
9,O0010,2026-03-05,C026,P005,2,Debit Card,Shipped,Fatima Noor,Srinagar,North,Regular,Power Bank,Electronics,1199,VoltPlus,3,5,Thursday,Fatima Noor,2398

In [15]:
print("Sales by Category:")

category_sales = processed_data.groupby(
    "Category"
)["Calculated_Total"].sum().sort_values(ascending=False)

display(category_sales)

Sales by Category:

Category
Home & Kitchen    243913
Electronics       177821
Clothing          168033
Sports            116736
Books              35004
Name: Calculated_Total, dtype: int64

In [16]:
print("Top Performing Products:")

product_sales = processed_data.groupby(
    ["Product_ID", "Product_Name"]
)["Calculated_Total"].sum().sort_values(ascending=False)

display(product_sales.head(10))

Top Performing Products:

Product_ID  Product_Name
P011        Air Fryer              124975
P008        Sneakers               116961
P004        Smart Watch            115465
P009        Coffee Maker            80477
P019        Cricket Bat             52479
P020        Dumbbell Set            47976
P006        Hoodie                  33579
P005        Power Bank              21582
P010        Electric Kettle         20986
P001        Wireless Headphones     19487
Name: Calculated_Total, dtype: int64

In [17]:
print("Order Status Summary:")

status_summary = processed_data["Order_Status"].value_counts()

display(status_summary)

Order Status Summary:

Order_Status
Delivered    79
Cancelled    25
Shipped      16
Name: count, dtype: int64

In [18]:
output_file = "Day9_Processed_Ecommerce_Dataset.csv"

processed_data.to_csv(
    output_file,
    index=False
)

print("SUCCESS! Final processed dataset exported as:")
print(output_file)

print("\nFile size:", os.path.getsize(output_file), "bytes")

SUCCESS! Final processed dataset exported as:
Day9_Processed_Ecommerce_Dataset.csv

File size: 18135 bytes

In [19]:
final_check = pd.read_csv("Day9_Processed_Ecommerce_Dataset.csv")

print("Final CSV loaded successfully!")
print("Rows:", final_check.shape[0])
print("Columns:", final_check.shape[1])

display(final_check.head())

Final CSV loaded successfully!
Rows: 120
Columns: 20

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand,Order_Month,Order_Day,Order_Day_Name,Customer_Name_Clean,Calculated_Total
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro,2,19,Thursday,Harsh Vardhan,4998
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear,1,25,Sunday,Ishita Gupta,1798
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech,2,26,Thursday,Karan Joshi,3299
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress,3,4,Wednesday,Maryam Khan,2997
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew,3,29,Sunday,Reyansh Jain,17495